DROP TABLE IF EXISTS TBL_USERS;
 
CREATE TABLE TBL_USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  pass VARCHAR(250) NOT NULL,
  rol INT NOT NULL
);


DROP TABLE IF EXISTS TBL_PRODUCTS;
 
CREATE TABLE TBL_PRODUCTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  price VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS TBL_SHOPPINGCARTS;
 
CREATE TABLE TBL_SHOPPINGCARTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  idUser INT NOT NULL,
  idProduct INT NOT NULL,
  cat INT NOT NULL
);